config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { :registrations => 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' } do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  # TODO: Consider using the "shallow" option for :pictures / :statuses
  resources :users, only: [:show, :index, :destroy] do
    resources :pictures
    resources :statuses
    resources :posts, only: [:show, :edit, :new, :destroy, :index]
  end
  resources :posts, only: [:show, :edit, :new, :destroy, :index]
  resources :pictures
  resources :statuses
  
  resources :likes, only: [:create, :destroy]

  resources :friendships, only: [:index] do
    post :send_request, on: :collection
    post :accept_request, on: :collection
    post :unfriend, on: :collection
  end
  root to: "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :authenticate_user!
  
  def show
    set_status
  end

  def new
    @status = current_user.statuses.build
  end

  def create
    @status = current_user.statuses.build(status_params)
    respond_to do |format|
      if @status.save
        current_user.posts.create(postable: @status)
        format.html { redirect_to user_path(current_user), notice: 'Status successfully created. ' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    set_status
  end

  def update
    set_status
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    set_status
    redirect_to picture_path(@status) unless current_user == @status.user
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_path, notice: 'Status was successfully deleted.' }
    end
  end

  def index
    set_user
    @statuses = @user.statuses
  end

  private

  def set_user
    begin
      @user = User.find(params[:user_id])
    rescue ActiveRecord::RecordNotFound => es
      @user = current_user
    end
  end

  def set_status
    @status = Status.find(params[:id])
  end

  def status_params
    params.require(:status).permit(:body)
  end

end

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>

  <div class="field">
    <%= f.text_field :body, autofocus: true, autocomplete: "status" %>
  </div>

  <div class="actions">
    <%= f.submit "Post" %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<%= render "form" %>

app/views/statuses/index.html.erb
<h1><%= link_to @user.name, user_path(@user) %>'s Statuses</h1>
<% if current_user == @user %>
  <p><%= link_to "New Status", new_status_path %></p>
<% end %>

<ul>
<% @statuses.each do |status| %>
  <li>
    <%= link_to status.body, status_path(status) %> |
    <%= status.created_at %>
    <% if current_user == @user %>
      <br/>
      <%= link_to "Delete", status_path(status), method: :delete %> |
      <%= link_to "Edit", edit_status_path(status) %>
    <% end %>
  </li>
<% end %>
</ul>

<%= link_to "Back to user", user_path(@user) %>

app/views/statuses/new.html.erb
<%= render "form" %>

app/views/statuses/show.html.erb
<p>
  <%= @display_user = @status.user
    render "profile_picture"
  %>
  <%= @status.body %>
</p>

<p>
 <%= link_to "Show all statuses", statuses_path %>
</p>