config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { :registrations => 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' } do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  # TODO: Consider using the "shallow" option for :pictures / :statuses
  resources :users, only: [:show, :index, :destroy] do
    resources :pictures
    resources :statuses
    resources :posts, only: [:show, :edit, :new, :destroy, :index]
  end
  resources :posts, only: [:show, :edit, :new, :destroy, :index]
  resources :pictures
  resources :statuses
  
  resources :likes, only: [:create, :destroy]

  resources :friendships, only: [:index] do
    post :send_request, on: :collection
    post :accept_request, on: :collection
    post :unfriend, on: :collection
  end
  root to: "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  before_destroy :destroy_friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  # friends       
  has_many :friendships
  has_many :friends, class_name: "User", through: :friendships, dependent: :destroy

  # assets
  has_many :pictures
  has_many :statuses

  # posts
  has_many :posts
  
  # likes
  has_many :likes

  # profile
  has_one_attached :image

  def friendship_state(friend)
    # expects friend: a user
    return :none unless friends.exists?(friend.id)
    f_state = Friendship.where(user_id: id, friend_id: friend.id).first.state
    f_i_state = Friendship.where(user_id: friend.id, friend_id: id).first.state

    if f_state == "accepted" and f_i_state == "accepted"
      return :accepted
    elsif f_state == "accepted" and f_i_state == "invited"
      return :sent
    elsif f_state == "invited" and f_i_state == "accepted"
      return :pending_acceptance
    end

    return :none
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end


  private
  def destroy_friendships
    friendships.each do |friendship|
      friendship.destroy
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def destroy
    Friendship.where(user_id: current_user).or(
      Friendship.where(friend_id: current_user)).destroy_all
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @display_user = User.find(params[:id])
    if @display_user == current_user
      @status = current_user.statuses.build
      @picture = current_user.pictures.build
    end
    @posts = @display_user.posts
  end

  def index
    @users = User.all
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend_request_button.html.erb
<% unless @display_user.id === current_user.id
%>
  <% friendship_state = current_user.friendship_state(@display_user).to_s 
  %>
  <%# Note that using a hash to DRY these methods throws button_to way off.
      Unfruitful caution required.   %>
  <% if friendship_state ==  "sent" %>
    <%= button_to "Friend Request Sent", "", disabled: true %>
    <%= button_to "Cancel", unfriend_friendships_path, method: :post,
    params: {friendship:{friend_id: @display_user.id}}, remote: true %>
  <% elsif friendship_state == "accepted" %>
    <%= button_to "Unfriend", unfriend_friendships_path, method: :post,
    params: {friendship:{friend_id: @display_user.id}}, remote: true %>
  <% elsif friendship_state == "none" %>
    <%= button_to "Send Friend Request", send_request_friendships_path, 
    params: {friendship:{friend_id: @display_user.id}}, method: :post, remote: true %>
  <% elsif friendship_state == "pending_acceptance" %>
    <%= button_to "Accept Friend Request", accept_request_friendships_path,
    params: {friendship:{friend_id: @display_user.id}}, method: :post, remote: true %>
     
  <% end %>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul id="articles">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user_path(user) %>
      <%=
      @display_user = user 
      render "friend_request_button" %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb

<%= render "profile_picture"%>
<h2>
  <%= @display_user.name %>
  <%= render "friend_request_button" %>
</h2>
<p><%= link_to "Pictures", user_pictures_path(@display_user) %> </p>
<p><%= link_to "Statuses", user_statuses_path(@display_user) %>

<% if @display_user == current_user %>
  <%= render "posts/form" %>
<% end %>

<% @posts.each do |post| %>

  <p><%=
  @post = post
  render "posts/post"
  %></p>
<% end %>