config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { :registrations => 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' } do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  # TODO: Consider using the "shallow" option for :pictures / :statuses
  resources :users, only: [:show, :index, :destroy] do
    resources :pictures
    resources :statuses
    resources :posts, only: [:show, :edit, :new, :destroy, :index]
  end
  resources :posts, only: [:show, :edit, :new, :destroy, :index]
  resources :pictures
  resources :statuses
  
  resources :likes, only: [:create, :destroy]

  resources :friendships, only: [:index] do
    post :send_request, on: :collection
    post :accept_request, on: :collection
    post :unfriend, on: :collection
  end
  root to: "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/picture.rb
class Picture < ApplicationRecord
  # string:description
  has_one_attached :image
  #has_many :likes, as: :likeable
  #alias_attribute :likers, :users
  #has_many :users, through: :likes
  #belongs_to :album
  belongs_to :user
  has_many :posts, as: :postable
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  
  def show
    set_picture
  end

  def new
    @picture = current_user.pictures.build
  end

  def create
    @picture = current_user.pictures.build(create_picture_params)
    respond_to do |format|
      if @picture.save
        current_user.posts.create(postable: @picture)
        format.html { redirect_to pictures_path, notice: 'Picture successfully created. ' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    set_picture
  end

  def update
    set_picture
    respond_to do |format|
      if @picture.update(update_picture_params)
        format.html { redirect_to user_path(current_user), notice: 'Description successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    set_picture
    redirect_to picture_path(@picture) unless current_user == @picture.user
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully deleted.' }
    end
  end

  def index
    set_user
    @pictures = @user.pictures
  end

  private

  def set_user
    begin
      @user = User.find(params[:user_id])
    rescue ActiveRecord::RecordNotFound => es
      @user = current_user
    end
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def create_picture_params
    params.require(:picture).permit(:image, :description)
  end

  def update_picture_params
    params.require(:picture).permit(:description)
  end

end

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <div class="field">
    <%= f.label :image, "Upload Image" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description, autofocus: true, autocomplete: "description" %>
  </div>

  <div class="actions">
    <%= f.submit "Upload" %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<%= form_for(@picture) do |f| %>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description, autofocus: true, autocomplete: "description" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/pictures/index.html.erb
<h1><%= link_to @user.name, user_path(@user) %>'s Pictures</h1>
<% if current_user == @user %>
  <p><%= link_to "New Picture", new_picture_path%><p>
<% end %>
<% @pictures.each do |picture| %>
  <div style="float:left;">
    <%= link_to image_tag(picture.image.variant(resize: '300x300!')), picture_path(picture) %>
  </div>
<% end %>

app/views/pictures/new.html.erb
<h1>Upload an Image </h1>
<%= render 'form' %>

app/views/pictures/show.html.erb
<h1>Picture by <%= @picture.user.name %></h1>
<p><%= @picture.created_at %>
<p><%= @picture.description %></p>
<p>
<% if current_user == @picture.user %>
  <%= link_to("Edit description", edit_picture_path(@picture)) %> |
  <%= link_to("Delete", picture_path(@picture), method: :delete) %>
<% end %>
</p>
<p>
  <%= link_to("Back to #{@picture.user.name}'s pictures", user_pictures_path(@picture.user)) %>
</p>

<p><%= image_tag @picture.image %></p>