config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { :registrations => 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' } do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  # TODO: Consider using the "shallow" option for :pictures / :statuses
  resources :users, only: [:show, :index, :destroy] do
    resources :pictures
    resources :statuses
    resources :posts, only: [:show, :edit, :new, :destroy, :index]
  end
  resources :posts, only: [:show, :edit, :new, :destroy, :index]
  resources :pictures
  resources :statuses
  
  resources :likes, only: [:create, :destroy]

  resources :friendships, only: [:index] do
    post :send_request, on: :collection
    post :accept_request, on: :collection
    post :unfriend, on: :collection
  end
  root to: "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :liked_by_me?, :my_like

  def liked_by_me?(likeable)
    Like.where(
      user_id: current_user.id,
      likeable_id: likeable.id,
      likeable_type: likeable.class.name
    ).count > 0
  end

  def my_like(likeable)
    Like.where(
      user_id: current_user.id,
      likeable_id: likeable.id,
      likeable_type: likeable.class.name
    ).first
  end
  
  protected

  def configure_permitted_parameters
    attributes = [:name, :image]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_like_button.html.erb
<% if liked_by_me? @likeable %>
  <%= 
  @my_like = my_like(@likeable)
  button_to "Unlike", like_path(@my_like), method: :delete,
  params: {like:{id: @my_like.id}, remote: true} %>
<% elsif %>
  <%= button_to "Like", likes_path, method: :post,
  params: {like:{likeable_id:@likeable.id, likeable_type:@likeable.class.name}, remote: true} %>
<% end %>

app/views/application/_profile_picture.html.erb
<% if @display_user.image.attached? %>
  <%= image_tag @display_user.image.variant(resize: '64x64!'), class: "rounded-class" %><br/>
<% else %>
  <%= image_tag gravatar_image_url(@display_user.email, size: 64), height: 64, width: 64, class: "rounded-circle" %>
<% end %>